### PR TITLE
Add answers to 09-MultiParamTypeClasses/src/Exercises.hs

### PR DESCRIPTION
**Pull request by monadplus**
I was doing the exercises and I found the first two exercises of the chapter 9 not answered so I decided to make this PR. Maybe there's a reason why both exercises have no answer but just in case.

### CODE REVIEW

**Comment by i-am-tom** [comment]
Sorry for missing this - it's super not cool that this took me a year to notice 😓 

Worse still, I did actually fill these gaps in about six months ago, apparently! Again, really sorry for the delay, and I'm super grateful for your work anyway - I am sure your answers will have been found by others searching for them in the mean time.

If you ever find yourself near London, I will apologise in the form of your favourite hot/cold drink. ❤️

**Comment by monadplus** [comment]
Don't worry @i-am-tom . Actually, I want to thank you for creating these exercises which helped me a lot a year ago. 

> If you ever find yourself near London, I will apologise in the form of your favourite hot/cold drink. heart

I'd love to chat with you someday too :-)

PS. It would be grate to add exercises on dependent types and linear types (when GHC 8.12)

**Comment by i-am-tom** [comment]
Thank you! I'm planning on doing just that :) There are still three more I'd really like to get done anyway (ScopedTypeVariables, TypeApplications, + AllowAmbiguousTypes), but I probably need to take a few days over the holidays to do some brutal editing first 😅

**Comment by monadplus** [comment]
Let me know if you need help.

**Pull request closed without merging**
