### PR TITLE
GADTs Exercises.hs without ConstraintKinds

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**

### CODE REVIEW

**Comment by i-am-tom** [comment]
Hey! I'm not sure I see how ConstraintKinds would allow us to write any more of these?

**Comment by BebeSparkelSparkel** [comment]
```
data AnyList c where
  AnyNil :: AnyList c
  AnyCons :: c a => a -> AnyList c -> AnyList c

instance Show (AnyList Show) where
  show AnyNil = “[]”
  show (AnyCons h t) = show h ++ “:” ++ show t

show $ AnyCons “Hi” $ AnyCons 1 (AnyNil :: AnyList Show)
```

**Comment by i-am-tom** [comment]
Ah, I see - thanks! I'm leaning towards not worrying about this for two reasons:

1. ConstraintKinds hasn't been introduced at this point, so it's not implied. If anyone _does_ know how to use ConstraintKinds and wrote what you are suggesting, I'd say they're pretty comfortable with the point it's making anyway :smile: I worry about introducing these terms before their explanation simply because it might be intimidating to newer Haskellers.

2. The first part says, `[write] a list that can take /any/ type, without any constraints.` - anyone who didn't already have an understanding of ConstraintKinds wouldn't have written your example, even in the face of those questions. Certainly, your particular list is a true list of "any types" for _very few_ `c` values!

**Comment by BebeSparkelSparkel** [comment]
All good points

**Comment by i-am-tom** [comment]
:) Thanks for the discussion, though!

**Comment by BebeSparkelSparkel** [comment]
NP, if I have any other suggestions I'll submit them

**Pull request closed without merging**
